# Generated by Django 4.2 on 2025-12-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория ПК',
                'verbose_name_plural': 'Категории ПК',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за час (₴)')),
                ('description', models.TextField(blank=True, verbose_name='Описание тарифа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='tariffs.category', verbose_name='Категория ПК')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
