# Generated by Django 4.2 on 2026-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за час (₽)'),
        ),
    ]
