# Generated by Django 4.2 on 2025-12-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер места')),
                ('title', models.CharField(max_length=200, verbose_name='Название места/зоны')),
                ('description', models.TextField(blank=True, verbose_name='Описание места/зоны')),
                ('specs', models.TextField(blank=True, verbose_name='Характеристики ПК')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно для бронирования')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Фото места')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tariffs.category', verbose_name='Категория ПК')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tariffs.tariff', verbose_name='Тариф по умолчанию')),
            ],
            options={
                'verbose_name': 'Место/Зона',
                'verbose_name_plural': 'Места/Зоны',
            },
        ),
    ]
