# Generated by Django 4.2 on 2026-01-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['number'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='specs',
        ),
        migrations.AddField(
            model_name='place',
            name='cpu',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Процессор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='gpu',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Видеокарта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='headset',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Гарнитура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='keyboard',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Клавиатура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='monitor',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Монитор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='mouse',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Мышь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='ram',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='ОЗУ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
