# Generated by Django 4.2 on 2026-01-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
        ('places', '0002_alter_place_options_remove_place_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_active',
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cpu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='gpu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='headset',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='keyboard',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='monitor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='mouse',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='ram',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariff'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
