# Generated by Django 4.2 on 2026-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_news_text_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
