# Generated by Django 4.2 on 2026-05-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('cashier', 'Сотрудник стойки'), ('admin', 'Администратор')], default='user', max_length=10),
        ),
    ]
