# Generated by Django 4.2 on 2026-05-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('cashier', 'Сотрудник'), ('admin', 'Администратор')], default='user', max_length=10),
        ),
    ]
