# Generated by Django 4.2 on 2026-04-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена без скидки'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
    ]
