# Generated by Django 4.2 on 2026-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_discount_percent_booking_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
    ]
