# Generated by Django 4.2 on 2026-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)'),
        ),
    ]
